# Generated by Django 4.1.7 on 2023-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
