# Generated by Django 4.1.7 on 2023-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_profil_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=800)),
                ('Due_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('Created_Date', models.DateField(auto_now_add=True)),
                ('Updated_Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20)),
                ('todo', models.ManyToManyField(to='users.todo')),
            ],
        ),
    ]
