# Generated by Django 4.1.7 on 2023-03-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Updated_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
