# Generated by Django 4.1.7 on 2023-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_todo_due_date_alter_todo_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
