# Generated by Django 4.1.7 on 2023-03-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_todo_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TAGS',
            new_name='TAG',
        ),
    ]
