# Generated by Django 4.1.7 on 2023-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='tag_name',
            field=models.ManyToManyField(to='users.tag'),
        ),
    ]
