# Generated by Django 4.1.7 on 2023-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_tag_todo_todo_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.CharField(max_length=30),
        ),
    ]
