# Generated by Django 4.1.7 on 2023-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tag_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='todo',
            field=models.ManyToManyField(to='users.todo'),
        ),
    ]
