# Generated by Django 4.1.7 on 2023-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_todo_tag_name_tag_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='tag_name',
            field=models.ManyToManyField(to='users.tag'),
        ),
    ]
